# Generated by Django 4.1.6 on 2023-02-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grade",
            old_name="name",
            new_name="course_code",
        ),
    ]
